import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ProductShell } from '@/components/product-shell';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export default async function JobDetailPage({ params }: { params: { jobId: string } }) {
  const supabase = createSupabaseServerClient();
  const { data: job } = await supabase.from('jobs').select('id, title, location, remote_type, employment_type, industry, description, requirements, responsibilities, external_url, is_verified, employers(name, verification_status)').eq('id', params.jobId).maybeSingle();
  if (!job) notFound();
  return <ProductShell sectionLabel="Job detail" title={job.title} subtitle={`${job.employers?.name ?? 'Employer not provided'} · ${job.location ?? 'Location not provided'}${job.remote_type ? ` · ${job.remote_type}` : ''}`} actions={<Link href="/jobs" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-900">Back to jobs</Link>}><div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><article className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Role overview</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-8 text-slate-700">{job.description ?? 'No description provided by the employer.'}</p>{job.responsibilities ? <><h2 className="mt-8 text-xl font-semibold text-slate-950">Responsibilities</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-8 text-slate-700">{job.responsibilities}</p></> : null}{job.requirements ? <><h2 className="mt-8 text-xl font-semibold text-slate-950">Requirements</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-8 text-slate-700">{job.requirements}</p></> : null}</article><aside className="rounded-[1.75rem] bg-emerald-950 p-6 text-white shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-300">Application</p><h2 className="mt-3 text-2xl font-semibold">Ready to take the next step?</h2><p className="mt-3 text-sm leading-7 text-white/70">Sign in to review your profile match and create an application for this role.</p><Link href={`/auth/login?next=/jobs/${job.id}`} className="mt-6 inline-flex rounded-full bg-emerald-500 px-5 py-3 text-sm font-semibold text-white">Sign in to apply</Link></aside></div></ProductShell>;
}
