import Link from 'next/link';
import { ProductShell } from '@/components/product-shell';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export default async function JobsPage() {
  const supabase = createSupabaseServerClient();
  const [{ data: jobs, error }, { data: auth }] = await Promise.all([supabase.from('jobs').select('id, title, location, remote_type, employment_type, industry, salary_min, salary_max, currency, is_verified, employers(name)').order('published_at', { ascending: false }).limit(50), supabase.auth.getUser()]);
  const rows = jobs ?? [];

  return <ProductShell sectionLabel="Job discovery" title="Find work worth applying for." subtitle="Browse live opportunities from the marketplace. Save or apply only after reviewing the role and its match explanation." actions={<Link href={auth.user ? '/career-passport' : '/auth/login'} className="rounded-full bg-emerald-500 px-5 py-3 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(16,185,129,0.24)]">{auth.user ? 'Improve my match' : 'Sign in for matches'}</Link>} stats={[{ label: 'Open roles', value: error ? 'Unavailable' : String(rows.length), detail: error ? 'Job data could not be loaded' : 'Current results in the marketplace' }, { label: 'Verified employers', value: error ? 'Unavailable' : String(rows.filter((job) => job.is_verified).length), detail: 'Listings marked as verified' }, { label: 'Remote roles', value: error ? 'Unavailable' : String(rows.filter((job) => String(job.remote_type ?? '').toLowerCase().includes('remote')).length), detail: 'Roles with remote support' }]}>
    {error ? <div className="rounded-[1.5rem] border border-red-200 bg-red-50 p-6 text-sm text-red-700">Jobs could not be loaded: {error.message}</div> : rows.length ? <div className="grid gap-4">{rows.map((job) => <article key={job.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-[0_8px_20px_rgba(15,23,20,0.04)]"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-slate-500">{job.employers?.name ?? 'Employer not provided'}</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{job.title}</h2><p className="mt-2 text-sm text-slate-600">{job.location ?? 'Location not provided'}{job.remote_type ? ` · ${job.remote_type}` : ''}{job.employment_type ? ` · ${job.employment_type}` : ''}</p>{job.industry ? <p className="mt-2 text-xs uppercase tracking-[0.16em] text-slate-400">{job.industry}</p> : null}</div><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-800">{job.is_verified ? 'Verified' : 'Unverified'}</span><Link href={`/jobs/${job.id}`} className="rounded-full bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Review role</Link></div></div></article>)}</div> : <div className="rounded-[1.5rem] border border-dashed border-slate-300 bg-white p-10 text-center"><p className="text-sm text-slate-600">No jobs are available yet.</p><p className="mt-2 text-sm text-slate-500">An administrator can publish opportunities from the operations dashboard.</p></div>}
  </ProductShell>;
}
